language: rust

rust:
        - stable
        - beta
        - nightly

os:
        - linux
        - windows

arch: amd64

cache: cargo 

dist:
        - bionic
        - server-2016

jobs:
        allow_failures:
                - rust: beta
                - rust: nightly
                - os: windows
                - dist: server-2016
        fast_finish: true

before_install:
        - sudo apt-get -y update
        - sudo apt-get -y upgrade
        - sudo apt-get -y install build-essential gcc libssl-dev pkg-config libsodium-dev opus-tools libopus-dev ffmpeg
