[package]
name = "redcord-rust"
version = "0.1.0"
authors = ["Seth Flynn <sethaflynn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.7"
directories = "3.0.1"
reqwest = { version = "0.10.8", features = ["json"] }
serde_json = "1.0.58"
tokio = { version = "0.2.0", features = ["full"] }
