name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build
    - name: test
      run: cargo test
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: redcord-debug
        path: target/debug/redcord